name: qr_maker_scan
description: A new Flutter project.

version: 1.2.0+12

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_plus: ^3.0.0
  custom_qr_generator: ^0.1.2
  mobile_scanner: ^2.1.0
  url_launcher: ^6.1.7
  blurrycontainer: ^1.0.2
  clipboard: ^0.1.3
  flutter_svg: ^1.1.6
  flutter_launcher_icons: ^0.11.0
  image_gallery_saver: ^1.7.1
  take_screenshot: ^0.0.2
  permission_handler: ^10.2.0
  toast: ^0.3.0
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.3.0
  qr_flutter: ^4.0.0
  pretty_qr_code: ^2.0.2
  lottie: ^2.2.0
  hive: ^2.2.3
  flutter_bloc: ^8.1.2
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
