name: qr_maker_scan
description: A new Flutter project.

version: 1.2.0+21

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_plus: ^5.0.0
  custom_qr_generator: ^0.1.2
  mobile_scanner: ^5.1.1
  url_launcher: ^6.1.7
  blurrycontainer: ^2.1.0
  clipboard: ^0.1.3
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  image_gallery_saver: ^2.0.3
  take_screenshot: ^0.0.2
  permission_handler: ^11.3.1
  toast: ^0.3.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.1.0
  qr_flutter: ^4.0.0
  pretty_qr_code: ^3.3.0
  lottie: ^3.1.2
  hive: ^2.2.3
  flutter_bloc: ^8.1.2
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/skenner_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
